/*
 * Predict with a CPSign classification model
 * Service that deploys a CPSign classification model and allows for predictions to be made by the deployed model.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@genettasoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.api.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * BadRequestError
 */
//@ApiModel(description = "BadRequestError")
public class BadRequestError extends ErrorResponse {

	@JsonProperty("fields")
//	@ApiModelProperty(required = true, value = "Relevant field(s)")
	private List<String> fields = new ArrayList<String>();

	public BadRequestError(int code, String message, List<String> fields) {
		super(code, message);
		this.fields = fields;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		BadRequestError badRequestError = (BadRequestError) o;
		return super.equals(badRequestError) &&
				Objects.equals(this.fields, badRequestError.fields);
	}

	@Override
	public int hashCode() {
		return Objects.hash(fields);
	}


	@Override
	public String toString() {
		return super.toString();
	}
}