/*
 * Predict with a CPSign classification model
 * Service that deploys a CPSign classification model and allows for predictions to be made by the deployed model.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@genettasoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.api.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

//import io.swagger.annotations.ApiModel;
//import io.swagger.annotations.ApiModelProperty;

/**
 * ErrorResponse
 */
//@ApiModel(description = "ErrorResponse")
public class ErrorResponse {
	@JsonProperty("code")
//	@ApiModelProperty(required = true, value = "HTTP status code", example="400")
	private final Integer code;

	@JsonProperty("message")
//	@ApiModelProperty(required = true, value = "Error message", example="Invalid argument")
	private final String message;

	public ErrorResponse(int code, String message) {
		this.code = code;
		this.message = message;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ErrorResponse error = (ErrorResponse) o;
		return Objects.equals(this.code, error.code) &&
				Objects.equals(this.message, error.message);
	}

	@Override
	public int hashCode() {
		return Objects.hash(code, message);
	}

//	public JsonObject toJSON(){
//		JsonObject jsonResponse = new JsonObject();
//
//		jsonResponse.put("code", code);
//		jsonResponse.put("message", message);
//
//		return jsonResponse;
//	}
	
	@Override
	public String toString() {
		try {
			return new ObjectMapper().writeValueAsString(this);
		} catch (JsonProcessingException e) {
			e.printStackTrace();
			return "Error Reponse code=" + code + ", msg=" + message;
		}
	}

}

