/*
 * Predict with a CPSign classification model
 * Service that deploys a CPSign classification model and allows for predictions to be made by the deployed model.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@genettasoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.arosbio.api.model;

import java.util.List;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Classification
 */
public class ClassificationResult   {
	@JsonProperty("smiles")
	@NotNull
	private final String smiles;

	@JsonProperty("prediction")
	private List<PValueMapping> prediction;
	
	@JsonProperty("modelName")
	@NotNull
	private final String modelName;

	public ClassificationResult(List<PValueMapping> pvalues, String smiles, String modelName) {
		this.smiles = smiles;
		this.prediction = pvalues;
		this.modelName = modelName;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ClassificationResult classification = (ClassificationResult) o;
		return Objects.equals(this.smiles, classification.smiles) &&
				Objects.equals(this.prediction, classification.prediction) &&
				Objects.equals(this.modelName, classification.modelName);
	}

	@Override
	public int hashCode() {
		return Objects.hash(smiles, prediction, modelName);
	}

}

