/*
 * Predict with a CPSign classification model
 * Service that deploys a CPSign classification model and allows for predictions to be made by the deployed model.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@genettasoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.arosbio.api.model;

import java.util.Objects;

import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.NotNull;

import com.arosbio.commons.MathUtils;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Mapping of label to predicted p-value
 */
public class PValueMapping {
	@JsonProperty("label")
	private final String label;

	@JsonProperty("pValue")
	@NotNull
	@DecimalMin("0.0") @DecimalMax("1.0")
	private final Double pValue;

	public PValueMapping(String label, Double pvalue) {
		this.label = label;
		this.pValue = MathUtils.roundTo3significantFigures(pvalue);
	}
	
	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PValueMapping pvalueMapping = (PValueMapping) o;
		return Objects.equals(this.label, pvalueMapping.label) &&
				Objects.equals(this.pValue, pvalueMapping.pValue);
	}

	@Override
	public int hashCode() {
		return Objects.hash(label, pValue);
	}

}