ARG BASE
ARG WAR_FILE=cp_regression-2.0.0-SNAPSHOT.war
FROM $BASE as builder

#FROM jetty:9-jdk11
FROM jetty:11.0.14-jre17
# generalize this here and perhaps set this as an argument or env variable
COPY --from=builder /app/cp_classification/target/${WAR_FILE} /var/lib/jetty/webapps/ROOT.war

RUN mkdir /var/lib/jetty/models/
