swagger: '2.0'
info:
  title: Predict with a CPSign classification model
  description: Service that deploys a CPSign classification model and allows for predictions to be made by the deployed model.
  version: 0.1.0
  contact:
    email: "info@genettasoft.com"

paths:

  /predict:
    post:
      summary: Make a prediction on the given SMILES
      consumes: 
      - "multipart/form-data"
      produces: 
      - "application/json"
      parameters: 
      - name: "confidence"
        in: "formData"
        description: "The desired confidence of the prediction"
        required: true
        type: "number"
        maximum: 1
        minimum: 0
        default: 0.8
        format: "double"
      - name: "smiles"
        in: "formData"
        description: "Compound structure notation using SMILES notation"
        required: true
        type: "string"
        default: "CCCCC=O"

      responses:
        200:
          description: "OK"
          schema:
            $ref: '#/definitions/Classification'
        503:
          description: "Service not available"
          schema:
            $ref: "#/definitions/Error"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/BadRequestError"
        500:
          description: "Prediction error"
          schema:
            $ref: "#/definitions/Error"

definitions:

  PValueMapping:
    type: "object"
    required:
      - "label"
      - "pValue"
    properties:
      label:
        type: "string"
        description: "Label"
      pValue:
        type: "number"
        format: "double"
        description: "p-value (or null)"
        minimum: 0.0
        maximum: 1.0
    description: "Mapping of label to predicted p-value"

  Classification:
    type: "object"
    required:
    - "smiles"
    properties:
      smiles:
        type: "string"
        description: "SMILES string for the molecule used in the prediction"
      prediction:
        type: "array"
        description: "Predicted p-values for each label"
        items:
          $ref: '#/definitions/PValueMapping'
              
  Error:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
        description: "HTTP status code"
      message:
        type: "string"
        description: "Error message"
    description: "Error"
  
  BadRequestError:
    type: "object"
    required:
    - "code"
    - "fields"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
        description: "HTTP status code"
      message:
        type: "string"
        description: "Error message"
      fields:
        type: "array"
        description: "Relevant field(s)"
        items:
          type: "string"
    description: "BadRequestError"
    
