openapi: '3.0.0'
info:
  title: Predict CPSign model
  description: Service that deploys a CPSign model and allows for predictions to be made by the deployed model.
  version: 0.1.0
  contact:
    email: "info@genettasoft.com"

paths:
  /predict:
    post:
      summary: Make a prediction on the given SMILES
      parameters: 
        - in: query
          name: confidence
          schema:
            type: "number"
            default: 0.8
            format: double
      requestBody:
        description: SMILES string for molecule to predict on
        required: true
        content:
          text/plain:
            schema:
              type: string
      
      responses:
        '200':
          description: A prediction, either a Regression or a Classification prediction depending on the model.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/responses/Regression'
                  - $ref: '#/components/responses/Classification'
        '400':
          description: The given SMILES could not be parsed

components:

  schemas:
  
    PValueMapping:
      type: "object"
      required:
        - "label"
        - "pValue"
      properties:
        label:
          type: "string"
          description: "Label"
        pValue:
          type: "number"
          format: "double"
          description: "p-value (or null)"
          minimum: 0.0
          maximum: 1.0
      description: "Mapping of label to predicted p-value"

  responses:
    
    Classification:
      description: The results from a classification
      content:
        application/json:
          schema:
            type: "array"
            description: "Predicted p-values for each label"
            items:
              $ref: '#/components/schemas/PValueMapping'
              
        
    Regression:
      description: The results from a regression
      content:
        application/json:
          schema:
            type: object
            properties:
              minValue:
                type: "number"
                format: "double"
                description: "Predicted lower range"
              maxValue:
                type: "number"
                format: "double"
                description: "Predicted upper range"
