apiVersion: v1
kind: Template
metadata:
    name: classification-deploy-template
    annotations:
        description: "Deploy a classification prediction service"
        tags: "cpsign, classification, cpsign-prediction-service"
objects:

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
        name: cpsign-classification-${MODEL_ID}
    labels:
        app: cpsign-classification-${MODEL_ID}
    spec:
        strategy:
            type: Rolling
            rollingParams:
            updatePeriodSeconds: 1
            intervalSeconds: 1
            timeoutSeconds: 600
            maxUnavailable: 25%
            maxSurge: 25%
            resources: {}
            activeDeadlineSeconds: 21600
        triggers:
         - type: ImageChange
           imageChangeParams:
               automatic: true
               containerNames:
                   - cpsign-classification-${MODEL_ID}
               from:
                   kind: ImageStreamTag
                   name: 'cpsign-classification:latest'
         - type: ConfigChange
        replicas: 1
        selector:
            deploymentconfig: cpsign-classification-${MODEL_ID}
        template:
            metadata:
                labels:
                    app: cpsign-classification-${MODEL_ID}
                    deploymentconfig: cpsign-classification-${MODEL_ID}
            spec:
                containers:
                  - name: cpsign-classification-${MODEL_ID}
                    image: cpsign-classification:latest
                    ports: 
                      - containerPort: 8080
                        protocol: TCP
                    env:
                      - name: modelurl
                        value: ${JAR_URL}
                    terminationMessagePath: /dev/termination-log
                    imagePullPolicy: Always
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
            dnsPolicy: ClusterFirst
    
  - apiVersion: v1
    kind: Service
    metadata:
        name: cpsign-classification-${MODEL_ID}
        labels:
            app: cpsign-classification-${MODEL_ID}
    spec:
        ports:
          - name: 8080-tcp
            protocol: TCP
            port: 8080
            targetPort: 8080
        selector:
            deploymentconfig: cpsign-classification-${MODEL_ID}
    status:
        loadBalancer: {}

  - apiVersion: v1
    kind: Route
    metadata:
        name: cpsign-classification-${MODEL_ID}
    spec:
        host: m${MODEL_ID}.130.238.55.60.nip.io
        path: /swagger-jaxrs-server-1.0.0
        to:
            kind: Service
            name: cpsign-classification-${MODEL_ID}
            weight: 100
        port:
            targetPort: 8080-tcp

parameters:
    - name: JAR_URL
      description: URL from where the model jar file can be downloaded
    - name: MODEL_ID
      description: Unique id for the model.
