apiVersion: v1
kind: Template
metadata:
    name: classification-build-template
    annotations: 
        description: "Build the classification image"
        tags: "cpsign, classification"
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
        name: cpsign-classification
        namespace: cpsign-predictserver
    labels:
        app: cpsign-classification

  - apiVersion: v1
    kind: BuildConfig
    metadata:
        name: cpsign-classification
        namespace: cpsign-predictserver
        labels:
            app: cpsign-classification
    spec:
        runPolicy: Serial
        source:
            type: Git
            git:
                uri: 'ssh://git@bitbucket.org/genettasoft/cpsign.predictserver.git'
                ref: master
            contextDir: classification_eclipse-project
            sourceSecret:
                name: ${GIT_SOURCESECRET}
        strategy:
            type: Source
            sourceStrategy:
                from:
                    kind: ImageStreamTag
                    namespace: openshift
                    name: 'wildfly:10.1'
        output:
            to:
                kind: ImageStreamTag
                name: 'cpsign-classification:latest'
parameters:
  - name: GIT_SOURCESECRET
    description: Secret containing a private key to be used to access git repo

